name: build and deploy main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /quote-generator
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install packages
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Export static files
        run: yarn export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out